4 push admin to vps
wibedev-team/datachain-back pull request #8
Opened 2023-07-27 10:35 UTC by romanchechyotkin

2023-08-01 06:26 UTC, habdevs requested changes
непонятно это всё на сервере происходит или можно с локали стартануть
также сделай более подробное описание запуска в README

2023-08-01 06:26 UTC, habdevs commented on Readme.md
> +    cd datachain-admin
bash: cd: datachain-admin: No such file or directory

2023-08-01 06:26 UTC, habdevs commented on Readme.md
> +    curl https://188.225.44.3:8080/admin
Failed to connect to 188.225.44.3 port 8080 after 2244 ms: Couldn't connect to server

2023-08-01 12:24 UTC, habdevs requested changes
про удаленный сервер лучше для себя оставь так как доступы только у тебя

2023-08-01 12:24 UTC, habdevs commented on local.docker-compose.yaml
> +    driver: bridge
не оставляй висячие строки

2023-08-01 12:24 UTC, habdevs commented on Readme.md
> +# ВХОДНЫЕ ДАННЫЕ
какие данные в итоге для входа?
линк какой для входа на локали там нет пути /admin или /login?

2023-08-01 14:38 UTC, romanchechyotkin commented on Readme.md
> +# ВХОДНЫЕ ДАННЫЕ
перенаправмит на нужный url
по поводу данных для входа, это два пользователя-админа, создал двух для личных тестов

2023-08-08 08:30 UTC, habdevs requested changes

2023-08-08 08:30 UTC, habdevs commented on Readme.md
> +# ВХОДНЫЕ ДАННЫЕ
а url какой будет?

2023-08-08 08:30 UTC, habdevs commented on cmd/main/main.go
>  	log.Fatal(engine.RunTLS(":8000", "admin.data-chainz.ru.crt", "admin.data-chainz.ru.key"))
используй 2 пробела во всем проекте

2023-08-11 10:49 UTC, romanchechyotkin commented
это для артема, чтобы он поднял локально и фетчил данные для фронта

2023-08-11 11:09 UTC, romanchechyotkin commented
пока url для админки ip адрес удаленного сервера

2023-08-11 12:59 UTC, habdevs approved these changes

2023-08-11 14:25 UTC, merged